apiVersion: v1
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          http:
            endpoint: 0.0.0.0:4318
    connectors:
      spanmetrics:
        exemplars:
          enabled: true
        histogram:
          explicit:
            buckets: [10ms, 50ms, 100ms, 200ms, 500ms, 1s, 5s, 10s]
    processors:
      batch:
    exporters:
      prometheus:
        endpoint: 0.0.0.0:8889
        enable_open_metrics: true
      debug:
        verbosity: detailed
      otlp:
        endpoint: tempo.tempo:4317
        tls:
          insecure: true
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp, spanmetrics, debug]
        metrics:
          receivers: [otlp, spanmetrics]
          processors: [batch]
          exporters: [prometheus]
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"config.yaml":"receivers:\n  otlp:\n    protocols:\n      http:\n        endpoint: 0.0.0.0:4318\nconnectors:\n  spanmetrics:\n    exemplars:\n      enabled: true\n    histogram:\n      explicit:\n        buckets: [10ms, 50ms, 100ms, 200ms, 500ms, 1s, 5s, 10s]\nprocessors:\n  batch:\nexporters:\n  prometheus:\n    endpoint: 0.0.0.0:8889\n    enable_open_metrics: true\n  debug:\n    verbosity: detailed\n  otlp:\n    endpoint: tempo.tempo:4317\n    tls:\n      insecure: true\nservice:\n  pipelines:\n    traces:\n      receivers: [otlp]\n      processors: [batch]\n      exporters: [otlp, spanmetrics, debug]\n    metrics:\n      receivers: [otlp, spanmetrics]\n      processors: [batch]\n      exporters: [prometheus]\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"otel-collector-config","namespace":"default"}}
  creationTimestamp: "2025-07-17T21:29:53Z"
  name: otel-collector-config
  namespace: default
  resourceVersion: "2573075"
  uid: ebc16b6c-e202-40fc-addb-4f500a505e5c
