[tox]
skipsdist = true

[testenv:pip-compile]
basepython = python3.12
description = Update the requirements.txt file
skip_install = true
deps =
    pip-tools>=7.4
commands =
    pip-compile --no-emit-index-url --annotate --upgrade --generate-hashes --strip-extras -o "{toxinidir}/docs/requirements.txt" "{toxinidir}/docs/requirements.in"
setenv =
    CUSTOM_COMPILE_COMMAND = tox -e pip-compile

[testenv:docs]
description = Render documentation
skip_install = true
deps =
    -r{toxinidir}/docs/requirements.txt
commands =
    make -C docs {posargs:html} SPHINXOPTS="-j 4 -n -W"
allowlist_externals =
    make
