---
version: 0.2

branches:
  default:
    stage: pre-merge
models:
  - env: &global_env
      CI: 'true'
      CIRCLE_ARTIFACTS: '/tmp'
      CIRCLE_NODE_TOTAL: "4"
      CIRCLE_TEST_REPORTS: '/tmp'
      CI_REPORTS: '/tmp'
      ENABLE_LOCAL_CACHE: "1"
      REPORT_TOKEN: 'report-token-1'
  - Git: &clone
      name: Pull repo
      repourl: '%(prop:git_reference)s'
      shallow: True
      retryFetch: True
      haltOnFailure: True
      # Machine Setup
  - ShellCommand: &update_hosts
      name: Update hosts
      command: sudo bash -c "echo '
               127.0.0.1     \
               bucketwebsitetester.s3-website-us-east-1.amazonaws.com
               ' >> /etc/hosts"
      haltOnFailure: True
  - ShellCommandWthSecrets: &aws-credentials
      name: Setup AWS Credentials
      command: bash %(prop:worker_path)s/aws.bash
      haltOnFailure: True
  - ShellCommandWithSecrets: &npm-install
      name: install modules
      command: npm install
      haltOnFailure: True
  - ShellCommand: &kill-s3
      name: Kill S3
      command: bash %(prop:worker_path)s/killandsleep.bash 8000
      haltOnFailure: True
  - ShellCommand: &kill-dmd
      name: Kill DMD
      command: bash %(prop:worker_path)s/killandsleep.bash 9990
      haltOnFailure: True
stages:
  pre-merge:
    worker: &master-worker
      type: docker
      path: eve/workers/build
      volumes: &default_volumes
        - '/home/eve/workspace'
    steps:
      - TriggerStages:
          name: Launch all nodes simultaneously
          stage_names:
            - node0
#            - node1
#            - node2
#            - node3
          waitForFinish: True
          haltOnFailure: True
  node0:
    worker: *master-worker
    steps:
      - Git: *clone
      - ShellCommand: *update_hosts
      - ShellCommand:
          command: rm -rf node_modules
#      - ShellCommandWithSecrets: *aws-credentials
      - ShellCommandWithSecrets: *npm-install
#      - ShellCommandWithSecrets:
#          command: bash -l tests.bash
#          env:
#            <<: *global_env
#            CIRCLE_NODE_INDEX: '0'
#          timeout: 120
#      - ShellCommandWithSecrets:
#          name: Linting
#          command: |
#            npm run --silent lint -- --max-warnings 0
#            npm run --silent lint_md
#            flake8 $(git ls-files "*.py")
#            yamllint $(git ls-files "*.yml")
#      - ShellCommandWithSecrets:
#          name: Unit Coverage
#          command: |
#            mkdir -p $CIRCLE_TEST_REPORTS/unit
#            npm run unit_coverage
#            npm run unit_coverage_legacy_location
#          env: *global_env
#          haltOnFailure: True
# testing with supervisor
#      - ShellCommand:
#          command: ln -s $PWD /home/eve/S3 && ls ~/S3
#      - ShellCommandWithSecrets:
#          name: Run all tests
#          command: sudo -E supervisord -c /etc/supervisor/supervisord.conf -n
#          env: 
#            <<: *global_env
#            CIRCLE_NODE_INDEX: '0'
#            WORK_DIR: /home/eve/S3
      - ShellCommandWithSecrets:
          name: Node 1 Tests
          command: |
            . ~/.bashrc &> /dev/null \
            && bash wait_for_local_port.bash 9991 40 \
            && npm run multiple_backend_test || exit 1
          env: 
            <<: *global_env
            CIRCLE_NODE_INDEX: '0'
          timeout: 120
      - ShellCommand: *kill-dmd
      - ShellCommandWithSecrets:
          command: ls -la && cat /tmp/*.txt
          env:
            <<: *global_env
          haltOnFailure: True
  node1:
    worker: *master-worker
    steps:
      - Git: *clone
      - ShellCommand: *update_hosts
      - ShellCommand:
          command: rm -rf node_modules
      - ShellCommandWithSecrets: *aws-credentials
      - ShellCommandWithSecrets: *npm-install
      - ShellCommandWithSecrets:
          command: bash -l tests.bash
          env:
            <<: *global_env
            CIRCLE_NODE_INDEX: '1'
      - ShellCommandWithSecrets:
          command: ls -la && cat /tmp/*.txt
          env:
            <<: *global_env
          haltOnFailure: True
  node2:
    worker: *master-worker
    steps:
      - Git: *clone
      - ShellCommand: *update_hosts
      - ShellCommand:
          command: rm -rf node_modules
      - ShellCommandWithSecrets: *aws-credentials
      - ShellCommandWithSecrets: *npm-install
      - ShellCommandWithSecrets:
          command: bash -l tests.bash
          env:
            <<: *global_env
            CIRCLE_NODE_INDEX: '2'
      - ShellCommandWithSecrets:
          command: ls -la && cat /tmp/*.txt
          env:
            <<: *global_env
          haltOnFailure: True
  node3:
    worker: *master-worker
    steps:
      - Git: *clone
      - ShellCommand: *update_hosts
      - ShellCommand:
          command: rm -rf node_modules
      - ShellCommandWithSecrets: *aws-credentials
      - ShellCommandWithSecrets: *npm-install
      - ShellCommandWithSecrets:
          command: bash -l tests.bash
          env:
            <<: *global_env
            CIRCLE_NODE_INDEX: '3'
      - ShellCommandWithSecrets:
          command: ls -la && cat /tmp/*.txt
          env:
            <<: *global_env
          haltOnFailure: True
