apiVersion: v1
data:
  config.yaml: |
    apiVersion: addons.metalk8s.scality.com
    kind: PrometheusConfig
    spec:
      rules:
        kube_apps:
          kube_job_not_completed:
            warning:
              hours: 168
      config:
        retention_size: 8GiB
kind: ConfigMap
metadata:
  creationTimestamp: "2025-07-17T19:10:46Z"
  labels:
    app.kubernetes.io/managed-by: salt
    heritage: salt
    metalk8s.scality.com/version: 130.0.1-dev
  name: metalk8s-prometheus-config
  namespace: metalk8s-monitoring
  resourceVersion: "3198"
  uid: ff4bfa6d-93ac-4ab8-8f16-747b85bb63fc
