---
name: lint

on:
  pull_request:
    branches-ignore:
      - 'q/*/**'

permissions:
  contents: read

jobs:
  prettier:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '22.23.1'
          cache: yarn
      - name: install dependencies
        run: yarn install --frozen-lockfile --network-concurrency 1
      - name: Prettier
        run: yarn run --silent prettier:check
